fix - ensure correct `useIsomorphicLayoutEffect` detection in React Native
satya164/use-latest-callback pull request #4
Opened 2023-08-07 18:28 UTC by andrejpavlovic

RE: https://github.com/satya164/use-latest-callback/issues/3

Ensure `useIsomorphicLayoutEffect` correctly detected in React Native environment, by using `use-isomorphic-layout-effect` library that supports this hook instead of rolling our own.

2023-08-16 13:02 UTC, andrejpavlovic commented
@satya164 Any chance you can review this?

2023-10-11 20:33 UTC, satya164 requested changes
Thank you for the PR and sorry for the delay.

Can you inline the code instead? I'd rather not add a dependency for such a simple logic.

2023-10-12 14:43 UTC, andrejpavlovic commented
Hi @satya164, I don't think it's possible to inline the code, since the way to most reliably detect React Native, is to have a separate `*.native.js` file. I could copy the files from `use-isomorphic-layout-effect` library, if you don't want to have an external dependency.

2023-10-12 15:01 UTC, satya164 commented
@andrejpavlovic yeah, that's what I meant by inlining. lets add a `*.native.ts` file

2023-10-19 14:38 UTC, satya164 commented
I have made the changes in https://github.com/satya164/use-latest-callback/commit/e9bd09d937ae2519c16efe03635c8db3fb10dfbc and published. So I'm closing the PR.

2023-10-19 14:38 UTC, closed without merging

2023-10-19 19:20 UTC, andrejpavlovic commented
@satya164 Thank you!